version: "2"
services:
  front-end:
    build:
      context: ./front-end
    depends_on:
      - express-server
    ports:
      - "3000:3000"
    env_file:
      - ./front-end/src/.env
    networks:
      - my-network

  express-server:
    build:
      context: ./express-server
    ports:
      - "8080:8080"
    networks:
      - my-network

  collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/otel-collector-config.yaml"]
    volumes:
      - './otel-collector-config.yaml:/otel-collector-config.yaml'
    ports:
      - "4318:4318"
    depends_on:
      - jaeger-all-in-one
    networks:
      - my-network

  jaeger-all-in-one:
    hostname: jaeger-all-in-one
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - my-network

networks:
  my-network:
